### ISSUE TITLE
regex rules are no longer working

### ISSUE THREAD

**Issue by JeromeGmail** [requestly/rules#7]
Hello,

This is a very useful tool, I really love it.  

I am trying to put a regex rule but it doesn't seem to work, even a very simple version like
https:\/\/(.*)\.html(.*)

I have validated that with ttps://regex101.com.

Many thanks,
Jerome

**Comment by sachinjain024** [comment]
Thanks @JeromeGmail for reaching out. We expect regex to be captured between slashes so a valid regex looks something like the following -

    /https:\/\/(.)\.html(.)

We support JS based regex so if you try any regex on regex101 make sure you select javascript from left rail.

Please have a look at the Regex Matches Operator Documentation here - https://www.requestly.in/blog/2018/06/15/requestly-rule-operators/

Let me know if you need face any issues.

**Comment by JeromeGmail** [comment]
Hi Sachin,

Many thanks for your quick reply. 
Sorry, github has removed my slashes.

I tried this basic regex and I am getting an error message. 
I am having similar issue if i tried the "replace host" section instead.

![image](https://user-images.githubusercontent.com/40068098/44023081-66dfd66e-9ee1-11e8-963d-9edff26bbf9d.png)

kind regards,
Jerome

**Comment by sachinjain024** [comment]
Hi @JeromeGmail 
To answer your question, you also need a trailing slash "/" so the rule should look like this

    Request Url Matches Regex /https:\/\/(.*)\.html/ig
    Destination https://$1.html?cache=132

If your use case is cache buster, we have a better way of doing that. Try [Query Param Rule](https://www.requestly.in/blog/2018/04/07/modify-queryparams-rule-documentation/)

Try this
<img width="1326" alt="screenshot 2018-08-14 16 12 54" src="https://user-images.githubusercontent.com/3108399/44087274-f4a7e1a2-9fdc-11e8-8565-236e8ce08d05.png">

Above approach will add 3 digit random number with every request which contains ".html"

Let us know if it helps your use case.

**Comment by JeromeGmail** [comment]
Amazing !!!!

Many thanks !

**Comment by sachinjain024** [comment]
Thanks @JeromeGmail for confirming issue is fixed. And glad to see your positive review on chrome store. Made my day! Closing this issue.
